# Generated by Django 4.0.4 on 2022-05-08 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, default='', max_length=2)),
                ('year', models.SmallIntegerField(null=True)),
                ('auto_class', models.CharField(choices=[('e', 'economy'), ('c', 'comfort'), ('b', 'business')], default='e', max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='VehiclePassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=30, verbose_name='Идентификационный номер (VIN)')),
                ('engine_volume', models.SmallIntegerField(verbose_name='Объем двигателя, куб.см')),
                ('engine_power', models.SmallIntegerField(verbose_name='Мощность двигателя, л.с.')),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='motorpool.auto')),
            ],
            options={
                'verbose_name_plural': 'Паспорта машин',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='motorpool.brand'),
        ),
        migrations.AddField(
            model_name='auto',
            name='options',
            field=models.ManyToManyField(to='motorpool.option'),
        ),
    ]
