# Generated by Django 4.0.4 on 2022-08-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0004_alter_auto_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepassport',
            name='auto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pts', to='motorpool.auto', verbose_name='Автомобиль'),
        ),
    ]
